package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.sql.Date;

/**
 * Adiestramiento generated by hbm2java
 */
public class Adiestramiento implements java.io.Serializable {

	private Integer idadiestramiento;
	private Mascotas mascotas;
	private Trabajadores trabajadores;
	private Date fechainicio;
	private Date fechafinal;
	private BigDecimal coste;

	public Adiestramiento() {
	}

	public Adiestramiento(Mascotas mascotas, Trabajadores trabajadores, Date fechainicio, Date fechafinal,
			BigDecimal coste) {
		this.mascotas = mascotas;
		this.trabajadores = trabajadores;
		this.fechainicio = fechainicio;
		this.fechafinal = fechafinal;
		this.coste = coste;
	}

	public Integer getIdadiestramiento() {
		return this.idadiestramiento;
	}

	public void setIdadiestramiento(Integer idadiestramiento) {
		this.idadiestramiento = idadiestramiento;
	}

	public Mascotas getMascotas() {
		return this.mascotas;
	}

	public void setMascotas(Mascotas mascotas) {
		this.mascotas = mascotas;
	}

	public Trabajadores getTrabajadores() {
		return this.trabajadores;
	}

	public void setTrabajadores(Trabajadores trabajadores) {
		this.trabajadores = trabajadores;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public Date getFechafinal() {
		return this.fechafinal;
	}

	public void setFechafinal(Date fechafinal) {
		this.fechafinal = fechafinal;
	}

	public BigDecimal getCoste() {
		return this.coste;
	}

	public void setCoste(BigDecimal coste) {
		this.coste = coste;
	}

}
