package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Adjuntosmascota generated by hbm2java
 */
public class Adjuntosmascota implements java.io.Serializable {

	private Integer idadjunto;
	private Mascotas mascotas;
	private Date fechaadjunto;
	private byte[] archivomascota;

	public Adjuntosmascota() {
	}

	public Adjuntosmascota(Mascotas mascotas, Date fechaadjunto, byte[] archivomascota) {
		this.mascotas = mascotas;
		this.fechaadjunto = fechaadjunto;
		this.archivomascota = archivomascota;
	}

	public Integer getIdadjunto() {
		return this.idadjunto;
	}

	public void setIdadjunto(Integer idadjunto) {
		this.idadjunto = idadjunto;
	}

	public Mascotas getMascotas() {
		return this.mascotas;
	}

	public void setMascotas(Mascotas mascotas) {
		this.mascotas = mascotas;
	}

	public Date getFechaadjunto() {
		return this.fechaadjunto;
	}

	public void setFechaadjunto(Date fechaadjunto) {
		this.fechaadjunto = fechaadjunto;
	}

	public byte[] getArchivomascota() {
		return this.archivomascota;
	}

	public void setArchivomascota(byte[] archivomascota) {
		this.archivomascota = archivomascota;
	}

}
