package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

/**
 * Archivosadjuntos generated by hbm2java
 */
public class Archivosadjuntos implements java.io.Serializable {

	private Integer idarchivo;
	private Chat chat;
	private String pesoarchivo;
	private String rutaarchivo;

	public Archivosadjuntos() {
	}

	public Archivosadjuntos(Chat chat, String pesoarchivo, String rutaarchivo) {
		this.chat = chat;
		this.pesoarchivo = pesoarchivo;
		this.rutaarchivo = rutaarchivo;
	}

	public Integer getIdarchivo() {
		return this.idarchivo;
	}

	public void setIdarchivo(Integer idarchivo) {
		this.idarchivo = idarchivo;
	}

	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	public String getPesoarchivo() {
		return this.pesoarchivo;
	}

	public void setPesoarchivo(String pesoarchivo) {
		this.pesoarchivo = pesoarchivo;
	}

	public String getRutaarchivo() {
		return this.rutaarchivo;
	}

	public void setRutaarchivo(String rutaarchivo) {
		this.rutaarchivo = rutaarchivo;
	}

}
