package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Ausenciaslaborales generated by hbm2java
 */
public class Ausenciaslaborales implements java.io.Serializable {

	private Integer idausencia;
	private Trabajadores trabajadores;
	private String tipoausencia;
	private Date fechainicioausencia;
	private Date fechafinalausencia;
	private String comentarios;

	public Ausenciaslaborales() {
	}

	public Ausenciaslaborales(Trabajadores trabajadores, String tipoausencia, Date fechainicioausencia,
			String comentarios) {
		this.trabajadores = trabajadores;
		this.tipoausencia = tipoausencia;
		this.fechainicioausencia = fechainicioausencia;
		this.comentarios = comentarios;
	}

	public Ausenciaslaborales(Trabajadores trabajadores, String tipoausencia, Date fechainicioausencia,
			Date fechafinalausencia, String comentarios) {
		this.trabajadores = trabajadores;
		this.tipoausencia = tipoausencia;
		this.fechainicioausencia = fechainicioausencia;
		this.fechafinalausencia = fechafinalausencia;
		this.comentarios = comentarios;
	}

	public Integer getIdausencia() {
		return this.idausencia;
	}

	public void setIdausencia(Integer idausencia) {
		this.idausencia = idausencia;
	}

	public Trabajadores getTrabajadores() {
		return this.trabajadores;
	}

	public void setTrabajadores(Trabajadores trabajadores) {
		this.trabajadores = trabajadores;
	}

	public String getTipoausencia() {
		return this.tipoausencia;
	}

	public void setTipoausencia(String tipoausencia) {
		this.tipoausencia = tipoausencia;
	}

	public Date getFechainicioausencia() {
		return this.fechainicioausencia;
	}

	public void setFechainicioausencia(Date fechainicioausencia) {
		this.fechainicioausencia = fechainicioausencia;
	}

	public Date getFechafinalausencia() {
		return this.fechafinalausencia;
	}

	public void setFechafinalausencia(Date fechafinalausencia) {
		this.fechafinalausencia = fechafinalausencia;
	}

	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

}
