package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chat generated by hbm2java
 */
public class Chat implements java.io.Serializable {

	private Integer idchat;
	private Trabajadores trabajadoresByDnitreceptoraux;
	private Trabajadores trabajadoresByDnitemisoraux;
	private Date fechacreacion;
	private boolean resuelto;
	private String motivo;
	private String otromotivo;
	private Set archivosadjuntoses = new HashSet(0);
	private Set mensajes = new HashSet(0);

	public Chat() {
	}

	public Chat(Trabajadores trabajadoresByDnitreceptoraux, Trabajadores trabajadoresByDnitemisoraux,
			Date fechacreacion, boolean resuelto, String motivo) {
		this.trabajadoresByDnitreceptoraux = trabajadoresByDnitreceptoraux;
		this.trabajadoresByDnitemisoraux = trabajadoresByDnitemisoraux;
		this.fechacreacion = fechacreacion;
		this.resuelto = resuelto;
		this.motivo = motivo;
	}

	public Chat(Trabajadores trabajadoresByDnitreceptoraux, Trabajadores trabajadoresByDnitemisoraux,
			Date fechacreacion, boolean resuelto, String motivo, String otromotivo, Set archivosadjuntoses,
			Set mensajes) {
		this.trabajadoresByDnitreceptoraux = trabajadoresByDnitreceptoraux;
		this.trabajadoresByDnitemisoraux = trabajadoresByDnitemisoraux;
		this.fechacreacion = fechacreacion;
		this.resuelto = resuelto;
		this.motivo = motivo;
		this.otromotivo = otromotivo;
		this.archivosadjuntoses = archivosadjuntoses;
		this.mensajes = mensajes;
	}

	public Integer getIdchat() {
		return this.idchat;
	}

	public void setIdchat(Integer idchat) {
		this.idchat = idchat;
	}

	public Trabajadores getTrabajadoresByDnitreceptoraux() {
		return this.trabajadoresByDnitreceptoraux;
	}

	public void setTrabajadoresByDnitreceptoraux(Trabajadores trabajadoresByDnitreceptoraux) {
		this.trabajadoresByDnitreceptoraux = trabajadoresByDnitreceptoraux;
	}

	public Trabajadores getTrabajadoresByDnitemisoraux() {
		return this.trabajadoresByDnitemisoraux;
	}

	public void setTrabajadoresByDnitemisoraux(Trabajadores trabajadoresByDnitemisoraux) {
		this.trabajadoresByDnitemisoraux = trabajadoresByDnitemisoraux;
	}

	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	public boolean isResuelto() {
		return this.resuelto;
	}

	public void setResuelto(boolean resuelto) {
		this.resuelto = resuelto;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public String getOtromotivo() {
		return this.otromotivo;
	}

	public void setOtromotivo(String otromotivo) {
		this.otromotivo = otromotivo;
	}

	public Set getArchivosadjuntoses() {
		return this.archivosadjuntoses;
	}

	public void setArchivosadjuntoses(Set archivosadjuntoses) {
		this.archivosadjuntoses = archivosadjuntoses;
	}

	public Set getMensajes() {
		return this.mensajes;
	}

	public void setMensajes(Set mensajes) {
		this.mensajes = mensajes;
	}

}
