package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.sql.Time;

/**
 * Citas generated by hbm2java
 */
public class Citas implements java.io.Serializable {

	private Integer idcita;
	private Mascotas mascotas;
	private Date fechacita;
	private String motivocita;
	private Time horacita;

	public Citas() {
	}

	public Citas(Mascotas mascotas, Date fechacita, Time horacita, String motivocita) {
		this.mascotas = mascotas;
		this.fechacita = fechacita;
		this.horacita = horacita;
		this.motivocita = motivocita;
	}

	public String getMotivocita() {
		return motivocita;
	}

	public void setMotivocita(String motivocita) {
		this.motivocita = motivocita;
	}

	public Integer getIdcita() {
		return this.idcita;
	}

	public void setIdcita(Integer idcita) {
		this.idcita = idcita;
	}

	public Mascotas getMascotas() {
		return this.mascotas;
	}

	public void setMascotas(Mascotas mascotas) {
		this.mascotas = mascotas;
	}

	public Date getFechacita() {
		return this.fechacita;
	}

	public void setFechacita(Date fechacita) {
		this.fechacita = fechacita;
	}

	public Time getHoracita() {
		return this.horacita;
	}

	public void setHoracita(Time horacita) {
		this.horacita = horacita;
	}

}
