package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private String dnicaux;
	private Personas personas;
	private Date fechaalta;
	private Set<Reclamaciones> reclamacioneses = new HashSet<>(0);

	public Clientes() {
	}

	public Clientes(Personas personas, Date fechaalta) {
		this.personas = personas;
		this.fechaalta = fechaalta;
	}

	public Clientes(Personas personas, Date fechaalta, Set<Reclamaciones> reclamacioneses) {
		this.personas = personas;
		this.fechaalta = fechaalta;
		this.reclamacioneses = reclamacioneses;
	}

	public String getDnicaux() {
		return this.dnicaux;
	}

	public void setDnicaux(String dnicaux) {
		this.dnicaux = dnicaux;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public Date getFechaalta() {
		return this.fechaalta;
	}

	public void setFechaalta(Date fechaalta) {
		this.fechaalta = fechaalta;
	}

	public Set<Reclamaciones> getReclamacioneses() {
		return this.reclamacioneses;
	}

	public void setReclamacioneses(Set<Reclamaciones> reclamacioneses) {
		this.reclamacioneses = reclamacioneses;
	}
}