package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Consultas generated by hbm2java
 */
public class Consultas implements java.io.Serializable {

	private Integer idconsulta;
	private Mascotas mascotas;
	private Date fechaconsulta;
	private String anamnesis;
	private String exploracion;
	private String diagnostico;
	private String tratamiento;
	private Set consultaservicioses = new HashSet(0);

	public Consultas() {
	}

	public Consultas(Mascotas mascotas, Date fechaconsulta) {
		this.mascotas = mascotas;
		this.fechaconsulta = fechaconsulta;
	}

	public Consultas(Mascotas mascotas, Date fechaconsulta, String anamnesis, String exploracion, String diagnostico,
			String tratamiento, Set consultaservicioses) {
		this.mascotas = mascotas;
		this.fechaconsulta = fechaconsulta;
		this.anamnesis = anamnesis;
		this.exploracion = exploracion;
		this.diagnostico = diagnostico;
		this.tratamiento = tratamiento;
		this.consultaservicioses = consultaservicioses;
	}

	public Integer getIdconsulta() {
		return this.idconsulta;
	}

	public void setIdconsulta(Integer idconsulta) {
		this.idconsulta = idconsulta;
	}

	public Mascotas getMascotas() {
		return this.mascotas;
	}

	public void setMascotas(Mascotas mascotas) {
		this.mascotas = mascotas;
	}

	public Date getFechaconsulta() {
		return this.fechaconsulta;
	}

	public void setFechaconsulta(Date fechaconsulta) {
		this.fechaconsulta = fechaconsulta;
	}

	public String getAnamnesis() {
		return this.anamnesis;
	}

	public void setAnamnesis(String anamnesis) {
		this.anamnesis = anamnesis;
	}

	public String getExploracion() {
		return this.exploracion;
	}

	public void setExploracion(String exploracion) {
		this.exploracion = exploracion;
	}

	public String getDiagnostico() {
		return this.diagnostico;
	}

	public void setDiagnostico(String diagnostico) {
		this.diagnostico = diagnostico;
	}

	public String getTratamiento() {
		return this.tratamiento;
	}

	public void setTratamiento(String tratamiento) {
		this.tratamiento = tratamiento;
	}

	public Set getConsultaservicioses() {
		return this.consultaservicioses;
	}

	public void setConsultaservicioses(Set consultaservicioses) {
		this.consultaservicioses = consultaservicioses;
	}

}
