package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

/**
 * Consultaservicios generated by hbm2java
 */
public class Consultaservicios implements java.io.Serializable {

	private ConsultaserviciosId id;
	private Consultas consultas;
	private Servicios servicios;
	private int cantidad;
	private boolean facturado;

	public Consultaservicios() {
	}

	public Consultaservicios(ConsultaserviciosId id, Consultas consultas, Servicios servicios, int cantidad,
			boolean facturado) {
		this.id = id;
		this.consultas = consultas;
		this.servicios = servicios;
		this.cantidad = cantidad;
		this.facturado = facturado;
	}

	public ConsultaserviciosId getId() {
		return this.id;
	}

	public void setId(ConsultaserviciosId id) {
		this.id = id;
	}

	public Consultas getConsultas() {
		return this.consultas;
	}

	public void setConsultas(Consultas consultas) {
		this.consultas = consultas;
	}

	public Servicios getServicios() {
		return this.servicios;
	}

	public void setServicios(Servicios servicios) {
		this.servicios = servicios;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public boolean isFacturado() {
		return this.facturado;
	}

	public void setFacturado(boolean facturado) {
		this.facturado = facturado;
	}

}
