package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

/**
 * ConsultaserviciosId generated by hbm2java
 */
public class ConsultaserviciosId implements java.io.Serializable {

	private int idconsultaaux;
	private int idservicioaux;

	public ConsultaserviciosId() {
	}

	public ConsultaserviciosId(int idconsultaaux, int idservicioaux) {
		this.idconsultaaux = idconsultaaux;
		this.idservicioaux = idservicioaux;
	}

	public int getIdconsultaaux() {
		return this.idconsultaaux;
	}

	public void setIdconsultaaux(int idconsultaaux) {
		this.idconsultaaux = idconsultaaux;
	}

	public int getIdservicioaux() {
		return this.idservicioaux;
	}

	public void setIdservicioaux(int idservicioaux) {
		this.idservicioaux = idservicioaux;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConsultaserviciosId))
			return false;
		ConsultaserviciosId castOther = (ConsultaserviciosId) other;

		return (this.getIdconsultaaux() == castOther.getIdconsultaaux())
				&& (this.getIdservicioaux() == castOther.getIdservicioaux());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdconsultaaux();
		result = 37 * result + this.getIdservicioaux();
		return result;
	}

}
