package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private Integer iddepartamento;
	private String nombredepartamento;
	private Set trabajadoreses = new HashSet(0);

	public Departamentos() {
	}

	public Departamentos(String nombredepartamento) {
		this.nombredepartamento = nombredepartamento;
	}

	public Departamentos(String nombredepartamento, Set trabajadoreses) {
		this.nombredepartamento = nombredepartamento;
		this.trabajadoreses = trabajadoreses;
	}

	public Integer getIddepartamento() {
		return this.iddepartamento;
	}

	public void setIddepartamento(Integer iddepartamento) {
		this.iddepartamento = iddepartamento;
	}

	public String getNombredepartamento() {
		return this.nombredepartamento;
	}

	public void setNombredepartamento(String nombredepartamento) {
		this.nombredepartamento = nombredepartamento;
	}

	public Set getTrabajadoreses() {
		return this.trabajadoreses;
	}

	public void setTrabajadoreses(Set trabajadoreses) {
		this.trabajadoreses = trabajadoreses;
	}

}
