package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion implements java.io.Serializable {

	private Integer iddireccion;
	private Provincias provincias;
	private String calle;
	private Set personases = new HashSet(0);

	public Direccion() {
	}

	public Direccion(Provincias provincias, String calle) {
		this.provincias = provincias;
		this.calle = calle;
	}

	public Direccion(Provincias provincias, String calle, Set personases) {
		this.provincias = provincias;
		this.calle = calle;
		this.personases = personases;
	}

	public Integer getIddireccion() {
		return this.iddireccion;
	}

	public void setIddireccion(Integer iddireccion) {
		this.iddireccion = iddireccion;
	}

	public Provincias getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Provincias provincias) {
		this.provincias = provincias;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public Set getPersonases() {
		return this.personases;
	}

	public void setPersonases(Set personases) {
		this.personases = personases;
	}

}
