package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

/**
 * Empleadosantiguos generated by hbm2java
 */
public class Empleadosantiguos implements java.io.Serializable {

	private EmpleadosantiguosId id;
	private Paises paises;

	public Empleadosantiguos() {
	}

	public Empleadosantiguos(EmpleadosantiguosId id, Paises paises) {
		this.id = id;
		this.paises = paises;
	}

	public EmpleadosantiguosId getId() {
		return this.id;
	}

	public void setId(EmpleadosantiguosId id) {
		this.id = id;
	}

	public Paises getPaises() {
		return this.paises;
	}

	public void setPaises(Paises paises) {
		this.paises = paises;
	}

}
