package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

/**
 * EmpleadosantiguosId generated by hbm2java
 */
public class EmpleadosantiguosId implements java.io.Serializable {

	private String apellidos;
	private String dni;
	private int idpaisaux;
	private String nombre;
	private String telefono;

	public EmpleadosantiguosId() {
	}

	public EmpleadosantiguosId(String apellidos, String dni, int idpaisaux, String nombre, String telefono) {
		this.apellidos = apellidos;
		this.dni = dni;
		this.idpaisaux = idpaisaux;
		this.nombre = nombre;
		this.telefono = telefono;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public int getIdpaisaux() {
		return this.idpaisaux;
	}

	public void setIdpaisaux(int idpaisaux) {
		this.idpaisaux = idpaisaux;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmpleadosantiguosId))
			return false;
		EmpleadosantiguosId castOther = (EmpleadosantiguosId) other;

		return ((this.getApellidos() == castOther.getApellidos()) || (this.getApellidos() != null
				&& castOther.getApellidos() != null && this.getApellidos().equals(castOther.getApellidos())))
				&& ((this.getDni() == castOther.getDni()) || (this.getDni() != null && castOther.getDni() != null
						&& this.getDni().equals(castOther.getDni())))
				&& (this.getIdpaisaux() == castOther.getIdpaisaux())
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this.getTelefono() != null
						&& castOther.getTelefono() != null && this.getTelefono().equals(castOther.getTelefono())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getApellidos() == null ? 0 : this.getApellidos().hashCode());
		result = 37 * result + (getDni() == null ? 0 : this.getDni().hashCode());
		result = 37 * result + this.getIdpaisaux();
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		return result;
	}

}
