package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Facturas generated by hbm2java
 */
public class Facturas implements java.io.Serializable {

	private Integer idfactura;
	private Personas personas;
	private Date fechafactura;
	private byte[] archivopdf;

	public Facturas() {
	}

	public Facturas(Personas personas, Date fechafactura, byte[] archivopdf) {
		this.personas = personas;
		this.fechafactura = fechafactura;
		this.archivopdf = archivopdf;
	}

	public Integer getIdfactura() {
		return this.idfactura;
	}

	public void setIdfactura(Integer idfactura) {
		this.idfactura = idfactura;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public Date getFechafactura() {
		return this.fechafactura;
	}

	public void setFechafactura(Date fechafactura) {
		this.fechafactura = fechafactura;
	}

	public byte[] getArchivopdf() {
		return this.archivopdf;
	}

	public void setArchivopdf(byte[] archivopdf) {
		this.archivopdf = archivopdf;
	}

}
