package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Grupomedicamentos generated by hbm2java
 */
public class Grupomedicamentos implements java.io.Serializable {

	private Integer idgrupo;
	private String nombregrupo;
	private Set medicamentoses = new HashSet(0);

	public Grupomedicamentos() {
	}

	public Grupomedicamentos(String nombregrupo) {
		this.nombregrupo = nombregrupo;
	}

	public Grupomedicamentos(String nombregrupo, Set medicamentoses) {
		this.nombregrupo = nombregrupo;
		this.medicamentoses = medicamentoses;
	}

	public Integer getIdgrupo() {
		return this.idgrupo;
	}

	public void setIdgrupo(Integer idgrupo) {
		this.idgrupo = idgrupo;
	}

	public String getNombregrupo() {
		return this.nombregrupo;
	}

	public void setNombregrupo(String nombregrupo) {
		this.nombregrupo = nombregrupo;
	}

	public Set getMedicamentoses() {
		return this.medicamentoses;
	}

	public void setMedicamentoses(Set medicamentoses) {
		this.medicamentoses = medicamentoses;
	}

}
