package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mascotas generated by hbm2java
 */
public class Mascotas implements java.io.Serializable {

	private int nchip;
	private Razamascota razamascota;
	private Personas personas;
	private String nombremascota;
	private Date fechanacimiento;
	private String sexo;
	private String observaciones;
	private Boolean esterilizado;
	private Date fechaadopcion;
	private Set citases = new HashSet(0);
	private Set vacunases = new HashSet(0);
	private Set pesoses = new HashSet(0);
	private Set adiestramientos = new HashSet(0);
	private Set adjuntosmascotas = new HashSet(0);
	private Set salases = new HashSet(0);
	private Set consultases = new HashSet(0);

	public Mascotas() {
	}

	public Mascotas(int nchip, Razamascota razamascota, String nombremascota, Date fechanacimiento, String sexo) {
		this.nchip = nchip;
		this.razamascota = razamascota;
		this.nombremascota = nombremascota;
		this.fechanacimiento = fechanacimiento;
		this.sexo = sexo;
	}

	public Mascotas(int nchip, Razamascota razamascota, Personas personas, String nombremascota, Date fechanacimiento,
			String sexo, String observaciones, Boolean esterilizado, Date fechaadopcion, Set citases, Set vacunases,
			Set pesoses, Set adiestramientos, Set adjuntosmascotas, Set salases, Set consultases) {
		this.nchip = nchip;
		this.razamascota = razamascota;
		this.personas = personas;
		this.nombremascota = nombremascota;
		this.fechanacimiento = fechanacimiento;
		this.sexo = sexo;
		this.observaciones = observaciones;
		this.esterilizado = esterilizado;
		this.fechaadopcion = fechaadopcion;
		this.citases = citases;
		this.vacunases = vacunases;
		this.pesoses = pesoses;
		this.adiestramientos = adiestramientos;
		this.adjuntosmascotas = adjuntosmascotas;
		this.salases = salases;
		this.consultases = consultases;
	}

	public int getNchip() {
		return this.nchip;
	}

	public void setNchip(int nchip) {
		this.nchip = nchip;
	}

	public Razamascota getRazamascota() {
		return this.razamascota;
	}

	public void setRazamascota(Razamascota razamascota) {
		this.razamascota = razamascota;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public String getNombremascota() {
		return this.nombremascota;
	}

	public void setNombremascota(String nombremascota) {
		this.nombremascota = nombremascota;
	}

	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Boolean getEsterilizado() {
		return this.esterilizado;
	}

	public void setEsterilizado(Boolean esterilizado) {
		this.esterilizado = esterilizado;
	}

	public Date getFechaadopcion() {
		return this.fechaadopcion;
	}

	public void setFechaadopcion(Date fechaadopcion) {
		this.fechaadopcion = fechaadopcion;
	}

	public Set getCitases() {
		return this.citases;
	}

	public void setCitases(Set citases) {
		this.citases = citases;
	}

	public Set getVacunases() {
		return this.vacunases;
	}

	public void setVacunases(Set vacunases) {
		this.vacunases = vacunases;
	}

	public Set getPesoses() {
		return this.pesoses;
	}

	public void setPesoses(Set pesoses) {
		this.pesoses = pesoses;
	}

	public Set getAdiestramientos() {
		return this.adiestramientos;
	}

	public void setAdiestramientos(Set adiestramientos) {
		this.adiestramientos = adiestramientos;
	}

	public Set getAdjuntosmascotas() {
		return this.adjuntosmascotas;
	}

	public void setAdjuntosmascotas(Set adjuntosmascotas) {
		this.adjuntosmascotas = adjuntosmascotas;
	}

	public Set getSalases() {
		return this.salases;
	}

	public void setSalases(Set salases) {
		this.salases = salases;
	}

	public Set getConsultases() {
		return this.consultases;
	}

	public void setConsultases(Set consultases) {
		this.consultases = consultases;
	}

}
