package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.sql.Time;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje implements java.io.Serializable {

	private Integer idmensaje;
	private Chat chat;
	private Date fecha;
	private Time hora;
	private String cuerpomensaje;

	public Mensaje() {
	}

	public Mensaje(Chat chat, Date fecha, Time hora) {
		this.chat = chat;
		this.fecha = fecha;
		this.hora = hora;
	}

	public Mensaje(Chat chat, Date fecha, Time hora, String cuerpomensaje) {
		this.chat = chat;
		this.fecha = fecha;
		this.hora = hora;
		this.cuerpomensaje = cuerpomensaje;
	}

	public Integer getIdmensaje() {
		return this.idmensaje;
	}

	public void setIdmensaje(Integer idmensaje) {
		this.idmensaje = idmensaje;
	}

	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Time getHora() {
		return this.hora;
	}

	public void setHora(Time hora) {
		this.hora = hora;
	}

	public String getCuerpomensaje() {
		return this.cuerpomensaje;
	}

	public void setCuerpomensaje(String cuerpomensaje) {
		this.cuerpomensaje = cuerpomensaje;
	}

}
