package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Paises generated by hbm2java
 */
public class Paises implements java.io.Serializable {

	private Integer idpais;
	private String nombrepais;
	private Set provinciases = new HashSet(0);
	private Set empleadosantiguoses = new HashSet(0);

	public Paises() {
	}

	public Paises(String nombrepais) {
		this.nombrepais = nombrepais;
	}

	public Paises(String nombrepais, Set provinciases, Set empleadosantiguoses) {
		this.nombrepais = nombrepais;
		this.provinciases = provinciases;
		this.empleadosantiguoses = empleadosantiguoses;
	}

	public Integer getIdpais() {
		return this.idpais;
	}

	public void setIdpais(Integer idpais) {
		this.idpais = idpais;
	}

	public String getNombrepais() {
		return this.nombrepais;
	}

	public void setNombrepais(String nombrepais) {
		this.nombrepais = nombrepais;
	}

	public Set getProvinciases() {
		return this.provinciases;
	}

	public void setProvinciases(Set provinciases) {
		this.provinciases = provinciases;
	}

	public Set getEmpleadosantiguoses() {
		return this.empleadosantiguoses;
	}

	public void setEmpleadosantiguoses(Set empleadosantiguoses) {
		this.empleadosantiguoses = empleadosantiguoses;
	}

}
