package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas implements java.io.Serializable {

	private String dni;
	private Direccion direccion;
	private String nombre;
	private String apellido;
	private int telefono;
	private String email;
	private Clientes clientes;
	private Set facturases = new HashSet(0);
	private Set mascotases = new HashSet(0);
	private Trabajadores trabajadores;

	public Personas() {
	}

	public Personas(String dni, Direccion direccion, String nombre, String apellido, int telefono, String email) {
		this.dni = dni;
		this.direccion = direccion;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.email = email;
	}

	public Personas(String dni, Direccion direccion, String nombre, String apellido, int telefono, String email,
			Clientes clientes, Set facturases, Set mascotases, Trabajadores trabajadores) {
		this.dni = dni;
		this.direccion = direccion;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.email = email;
		this.clientes = clientes;
		this.facturases = facturases;
		this.mascotases = mascotases;
		this.trabajadores = trabajadores;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Direccion getDireccion() {
		return this.direccion;
	}

	public void setDireccion(Direccion direccion) {
		this.direccion = direccion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Set getFacturases() {
		return this.facturases;
	}

	public void setFacturases(Set facturases) {
		this.facturases = facturases;
	}

	public Set getMascotases() {
		return this.mascotases;
	}

	public void setMascotases(Set mascotases) {
		this.mascotases = mascotases;
	}

	public Trabajadores getTrabajadores() {
		return this.trabajadores;
	}

	public void setTrabajadores(Trabajadores trabajadores) {
		this.trabajadores = trabajadores;
	}

}
