package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Pesos generated by hbm2java
 */
public class Pesos implements java.io.Serializable {

	private Integer idpeso;
	private Mascotas mascotas;
	private double peso;
	private Date fechapeso;

	public Pesos() {
	}

	public Pesos(Mascotas mascotas, double peso, Date fechapeso) {
		this.mascotas = mascotas;
		this.peso = peso;
		this.fechapeso = fechapeso;
	}

	public Integer getIdpeso() {
		return this.idpeso;
	}

	public void setIdpeso(Integer idpeso) {
		this.idpeso = idpeso;
	}

	public Mascotas getMascotas() {
		return this.mascotas;
	}

	public void setMascotas(Mascotas mascotas) {
		this.mascotas = mascotas;
	}

	public double getPeso() {
		return this.peso;
	}

	public void setPeso(double peso) {
		this.peso = peso;
	}

	public Date getFechapeso() {
		return this.fechapeso;
	}

	public void setFechapeso(Date fechapeso) {
		this.fechapeso = fechapeso;
	}

}
