package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private Integer idprovincia;
	private Paises paises;
	private String nombreprovincia;
	private Set direccions = new HashSet(0);

	public Provincias() {
	}

	public Provincias(Paises paises, String nombreprovincia) {
		this.paises = paises;
		this.nombreprovincia = nombreprovincia;
	}

	public Provincias(Paises paises, String nombreprovincia, Set direccions) {
		this.paises = paises;
		this.nombreprovincia = nombreprovincia;
		this.direccions = direccions;
	}

	public Integer getIdprovincia() {
		return this.idprovincia;
	}

	public void setIdprovincia(Integer idprovincia) {
		this.idprovincia = idprovincia;
	}

	public Paises getPaises() {
		return this.paises;
	}

	public void setPaises(Paises paises) {
		this.paises = paises;
	}

	public String getNombreprovincia() {
		return this.nombreprovincia;
	}

	public void setNombreprovincia(String nombreprovincia) {
		this.nombreprovincia = nombreprovincia;
	}

	public Set getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set direccions) {
		this.direccions = direccions;
	}

}
