package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores implements java.io.Serializable {

	private String nif;
	private String nombreproveedor;
	private int telefonoproveedor;
	private int emailproveedor;
	private Set suministrans = new HashSet(0);

	public Proveedores() {
	}

	public Proveedores(String nif, String nombreproveedor, int telefonoproveedor, int emailproveedor) {
		this.nif = nif;
		this.nombreproveedor = nombreproveedor;
		this.telefonoproveedor = telefonoproveedor;
		this.emailproveedor = emailproveedor;
	}

	public Proveedores(String nif, String nombreproveedor, int telefonoproveedor, int emailproveedor,
			Set suministrans) {
		this.nif = nif;
		this.nombreproveedor = nombreproveedor;
		this.telefonoproveedor = telefonoproveedor;
		this.emailproveedor = emailproveedor;
		this.suministrans = suministrans;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNombreproveedor() {
		return this.nombreproveedor;
	}

	public void setNombreproveedor(String nombreproveedor) {
		this.nombreproveedor = nombreproveedor;
	}

	public int getTelefonoproveedor() {
		return this.telefonoproveedor;
	}

	public void setTelefonoproveedor(int telefonoproveedor) {
		this.telefonoproveedor = telefonoproveedor;
	}

	public int getEmailproveedor() {
		return this.emailproveedor;
	}

	public void setEmailproveedor(int emailproveedor) {
		this.emailproveedor = emailproveedor;
	}

	public Set getSuministrans() {
		return this.suministrans;
	}

	public void setSuministrans(Set suministrans) {
		this.suministrans = suministrans;
	}

}
