package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Razamascota generated by hbm2java
 */
public class Razamascota implements java.io.Serializable {

	private Integer idraza;
	private Tipomascota tipomascota;
	private String nombreraza;
	private Set mascotases = new HashSet(0);

	public Razamascota() {
	}

	public Razamascota(Tipomascota tipomascota, String nombreraza) {
		this.tipomascota = tipomascota;
		this.nombreraza = nombreraza;
	}

	public Razamascota(Tipomascota tipomascota, String nombreraza, Set mascotases) {
		this.tipomascota = tipomascota;
		this.nombreraza = nombreraza;
		this.mascotases = mascotases;
	}

	public Integer getIdraza() {
		return this.idraza;
	}

	public void setIdraza(Integer idraza) {
		this.idraza = idraza;
	}

	public Tipomascota getTipomascota() {
		return this.tipomascota;
	}

	public void setTipomascota(Tipomascota tipomascota) {
		this.tipomascota = tipomascota;
	}

	public String getNombreraza() {
		return this.nombreraza;
	}

	public void setNombreraza(String nombreraza) {
		this.nombreraza = nombreraza;
	}

	public Set getMascotases() {
		return this.mascotases;
	}

	public void setMascotases(Set mascotases) {
		this.mascotases = mascotases;
	}

}
