package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Reclamaciones generated by hbm2java
 */
public class Reclamaciones implements java.io.Serializable {

	private Integer idreclamacion;
	private Clientes clientes;
	private Date fechareclamacion;
	private String reclamacion;

	public Reclamaciones() {
	}

	public Reclamaciones(Clientes clientes, Date fechareclamacion, String reclamacion) {
		this.clientes = clientes;
		this.fechareclamacion = fechareclamacion;
		this.reclamacion = reclamacion;
	}

	public Integer getIdreclamacion() {
		return this.idreclamacion;
	}

	public void setIdreclamacion(Integer idreclamacion) {
		this.idreclamacion = idreclamacion;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Date getFechareclamacion() {
		return this.fechareclamacion;
	}

	public void setFechareclamacion(Date fechareclamacion) {
		this.fechareclamacion = fechareclamacion;
	}

	public String getReclamacion() {
		return this.reclamacion;
	}

	public void setReclamacion(String reclamacion) {
		this.reclamacion = reclamacion;
	}

}
