package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Salas generated by hbm2java
 */
public class Salas implements java.io.Serializable {

	private int idsala;
	private String nombresala;
	private int capacidad;
	private String tiposala;
	private Set mascotases = new HashSet(0);

	public Salas() {
	}

	public Salas(int idsala, String nombresala, int capacidad, String tiposala) {
		this.idsala = idsala;
		this.nombresala = nombresala;
		this.capacidad = capacidad;
		this.tiposala = tiposala;
	}

	public Salas(int idsala, String nombresala, int capacidad, String tiposala, Set mascotases) {
		this.idsala = idsala;
		this.nombresala = nombresala;
		this.capacidad = capacidad;
		this.tiposala = tiposala;
		this.mascotases = mascotases;
	}

	public int getIdsala() {
		return this.idsala;
	}

	public void setIdsala(int idsala) {
		this.idsala = idsala;
	}

	public String getNombresala() {
		return this.nombresala;
	}

	public void setNombresala(String nombresala) {
		this.nombresala = nombresala;
	}

	public int getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(int capacidad) {
		this.capacidad = capacidad;
	}

	public String getTiposala() {
		return this.tiposala;
	}

	public void setTiposala(String tiposala) {
		this.tiposala = tiposala;
	}

	public Set getMascotases() {
		return this.mascotases;
	}

	public void setMascotases(Set mascotases) {
		this.mascotases = mascotases;
	}

}
