package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicios generated by hbm2java
 */
public class Servicios implements java.io.Serializable {

	private Integer idservicio;
	private String nombre;
	private BigDecimal preciobase;
	private BigDecimal preciopvp;
	private Integer cantidaTotal;
	private Set consultaservicioses = new HashSet(0);
	private Set suministrans = new HashSet(0);

	public Servicios() {
	}

	public Servicios(String nombre, BigDecimal preciobase, BigDecimal preciopvp, Integer cantidaTotal) {
		this.nombre = nombre;
		this.preciobase = preciobase;
		this.preciopvp = preciopvp;
		this.cantidaTotal = cantidaTotal;
	}

	public Servicios(String nombre, BigDecimal preciobase, BigDecimal preciopvp, Integer cantidaTotal, Set consultaservicioses,
			Set suministrans) {
		this.nombre = nombre;
		this.preciobase = preciobase;
		this.preciopvp = preciopvp;
		this.cantidaTotal = cantidaTotal;
		this.consultaservicioses = consultaservicioses;
		this.suministrans = suministrans;
	}

	public Integer getIdservicio() {
		return this.idservicio;
	}

	public void setIdservicio(Integer idservicio) {
		this.idservicio = idservicio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getPreciobase() {
		return this.preciobase;
	}

	public void setPreciobase(BigDecimal preciobase) {
		this.preciobase = preciobase;
	}

	public BigDecimal getPreciopvp() {
		return this.preciopvp;
	}

	public void setPreciopvp(BigDecimal preciopvp) {
		this.preciopvp = preciopvp;
	}

	public Integer getCantidaTotal() {
		return this.cantidaTotal;
	}

	public void setCantidaTotal(Integer cantidaTotal) {
		this.cantidaTotal = cantidaTotal;
	}

	public Set getConsultaservicioses() {
		return this.consultaservicioses;
	}

	public void setConsultaservicioses(Set consultaservicioses) {
		this.consultaservicioses = consultaservicioses;
	}

	public Set getSuministrans() {
		return this.suministrans;
	}

	public void setSuministrans(Set suministrans) {
		this.suministrans = suministrans;
	}

}
