package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

/**
 * Suministran generated by hbm2java
 */
public class Suministran implements java.io.Serializable {

	private Integer idsuministro;
	private Proveedores proveedores;
	private Servicios servicios;
	private int cantidadadquirida;

	public Suministran() {
	}

	public Suministran(Proveedores proveedores, Servicios servicios, int cantidadadquirida) {
		this.proveedores = proveedores;
		this.servicios = servicios;
		this.cantidadadquirida = cantidadadquirida;
	}

	public Integer getIdsuministro() {
		return this.idsuministro;
	}

	public void setIdsuministro(Integer idsuministro) {
		this.idsuministro = idsuministro;
	}

	public Proveedores getProveedores() {
		return this.proveedores;
	}

	public void setProveedores(Proveedores proveedores) {
		this.proveedores = proveedores;
	}

	public Servicios getServicios() {
		return this.servicios;
	}

	public void setServicios(Servicios servicios) {
		this.servicios = servicios;
	}

	public int getCantidadadquirida() {
		return this.cantidadadquirida;
	}

	public void setCantidadadquirida(int cantidadadquirida) {
		this.cantidadadquirida = cantidadadquirida;
	}

}
