package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipomascota generated by hbm2java
 */
public class Tipomascota implements java.io.Serializable {

	private Integer idtipo;
	private String nombretipo;
	private Set razamascotas = new HashSet(0);

	public Tipomascota() {
	}

	public Tipomascota(String nombretipo) {
		this.nombretipo = nombretipo;
	}

	public Tipomascota(String nombretipo, Set razamascotas) {
		this.nombretipo = nombretipo;
		this.razamascotas = razamascotas;
	}

	public Integer getIdtipo() {
		return this.idtipo;
	}

	public void setIdtipo(Integer idtipo) {
		this.idtipo = idtipo;
	}

	public String getNombretipo() {
		return this.nombretipo;
	}

	public void setNombretipo(String nombretipo) {
		this.nombretipo = nombretipo;
	}

	public Set getRazamascotas() {
		return this.razamascotas;
	}

	public void setRazamascotas(Set razamascotas) {
		this.razamascotas = razamascotas;
	}

}
