package PetnovaHN;
// Generated 23 ene 2025, 19:11:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Vacunas generated by hbm2java
 */
public class Vacunas implements java.io.Serializable {

	private Integer idvacuna;
	private Mascotas mascotas;
	private String nombre;
	private Date fechavacuna;

	public Vacunas() {
	}

	public Vacunas(Mascotas mascotas, String nombre, Date fechavacuna) {
		this.mascotas = mascotas;
		this.nombre = nombre;
		this.fechavacuna = fechavacuna;
	}

	public Integer getIdvacuna() {
		return this.idvacuna;
	}

	public void setIdvacuna(Integer idvacuna) {
		this.idvacuna = idvacuna;
	}

	public Mascotas getMascotas() {
		return this.mascotas;
	}

	public void setMascotas(Mascotas mascotas) {
		this.mascotas = mascotas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechavacuna() {
		return this.fechavacuna;
	}

	public void setFechavacuna(Date fechavacuna) {
		this.fechavacuna = fechavacuna;
	}

}
